# These are supported funding model platforms

github: [jafaeldon]
patreon: jafaeldon
open_collective: jafaeldon # Replace with a single Open Collective username
ko_fi: jafaeldon
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
